baseURL: http://example.org/
languageCode: en-us
title: ClÃ©mentine Boussange
theme: mini

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French) / es (Spanish) / da (Danish), default 'en'
defaultContentLanguage: en

# To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
hiddenPostSummaryInHomePage: false

social:
  # e.g.
  # github: your-github-link
  # twitter: your-github-link
  # stackoverflow: your-github-link


params:
  # Site Author
  author: ClÃ©mentine Boussange
  # Author biography
  bio: *IngÃ©nieure agronome, en mission (VSI) pour [Enfants du MÃ©kong](https://www.enfantsdumekong.com) ğŸ“ThaÃ¯lande Sud*
  Sawadi Kha ou Bonjour poli,
  "Si vous Ãªtes arrivÃ©s sur ce site c'est que vous devez dÃ©jÃ  bien connaitre l'objet de ma mission. Alors ici on ne parle plus de newsletters mais de sentiments, ressentiments, d'anecdotes et d'aventures. Bienvenus sur mon journal de bord, j'espÃ¨re que vous apprÃ©cierez de traverser avec moi ces 13 mois aux cÃ´tÃ©s des plus pauvres en ThaÃ¯lande du Sud ğŸŒ
  
  "Pour me contacter : clem.boussange@gmail "
  
  "Pour soutenir ma mission et faire un don : bit.ly/boussange "
  
  # Site Description, used in HTML meat
  description: Site web personnel


# To enable RSS, you could set `enableRSS: true`, default is `true`
enableRSS: true
showPowerBy: false
